# Running Quality Gates
name: PR - Develop

# When PR Updated
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - develop

jobs:
  analysis:
    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 현재 경로 및 상위 경로 체크를 해본다.
      - name: Check All Folder
        run: |
          ls

      # 자바 버전 설정
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '12.x'

      # Flutter 버전 설정
      - name: flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      # Sets Dart version
      - name: dart setup
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.1.5

      # run flutter pub get
      - run: flutter pub get

      # run build_runner
      - run: flutter pub run build_runner build --delete-conflicting-outputs

      # Install LCOV
      - name: Install LCOV
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      # Static analysis
      - name: Static analysis
        run: |
          flutter analyze
          flutter pub run dart_code_metrics:metrics analyze lib
          flutter pub run dart_code_metrics:metrics analyze test

      - name: Run test coverage
        shell: bash
        run: |
          chmod +rwx scripts/test-with-coverage.sh 
          scripts/test-with-coverage.sh

      - name: Upload LCOV report
        uses: actions/upload-artifact@v2
        with:
          name: lcov-report
          path: coverage/

      - name: Use Node.js to make badge
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Create coverage badge
        run: |
          npm init -y
          npm install
          npm install lcov2badge
          node scripts/generate_coverage_badge.js

      - name: Commit new badge
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'chore: upload badge'
          add: '.github/badges/coverage_badge.svg'