# Running Quality Gates
name: PR - Static Analysis

# When PR Updated
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - develop

jobs:
  analysis:
    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 현재 경로 및 상위 경로 체크를 해본다.
      - name: Check All Folder
        run: |
          ls

      # 자바 버전 설정
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '12.x'

      # Flutter 버전 설정
      - name: flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'

      # run flutter pub get
      - run: flutter pub get

      # run build_runner
      - run: flutter pub run build_runner build --delete-conflicting-outputs