# Running Quality Gates
name: PR - Static Analysis

# When PR Updated
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - develop

jobs:
  analysis:
    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      # Install LCOV
      - name: Install LCOV
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      # Static analysis
      - name: Static analysis
        run: |
          flutter analyze
          flutter pub run dart_code_metrics:metrics analyze lib
          flutter pub run dart_code_metrics:metrics analyze test

      - name: Run test coverage
        shell: bash
        run: scripts/test_with_coverage.sh

      - name: Upload LCOV report
        uses: actions/upload-artifact@v2
        with:
          name: lcov-report
          path: coverage/

      - name: Use Node.js to make badge
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Create coverage badge
        run: |
          npm init -y
          npm install
          npm install lcov2badge
          node scripts/coverage_badge_gen.js

      - name: Commit new badge
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'chore: upload badge'
          add: '.github/badges/coverage_badge.svg'